Package: zlib
Version: 1.2.3
Revision: 3
Maintainer: Marmalade Package Team <packages@ideaworkslabs.com>
Mkbs: zlib.mkb
Description: |
 zlib library for creating and reading zlib compressed data.
Libraries: z
Contents-Source:
 - zlib.mkb
 - zlib.mkf
 - README.rst
Contents:
 - upstream/zlib.h : h/zlib.h
 - upstream/zconf.h : h/zconf.h
 - README.rst
